// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CalculateCxy
List CalculateCxy(int m, int n, S4 hparam, S4 thetaYList, arma::vec ZOneDim, arma::vec qVec, arma::mat X);
RcppExport SEXP _bpgmm_CalculateCxy(SEXP mSEXP, SEXP nSEXP, SEXP hparamSEXP, SEXP thetaYListSEXP, SEXP ZOneDimSEXP, SEXP qVecSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< S4 >::type hparam(hparamSEXP);
    Rcpp::traits::input_parameter< S4 >::type thetaYList(thetaYListSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ZOneDim(ZOneDimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qVec(qVecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(CalculateCxy(m, n, hparam, thetaYList, ZOneDim, qVec, X));
    return rcpp_result_gen;
END_RCPP
}
// get_Z_mat
arma::mat get_Z_mat(arma::vec ZOneDim, int m, int n);
RcppExport SEXP _bpgmm_get_Z_mat(SEXP ZOneDimSEXP, SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ZOneDim(ZOneDimSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_Z_mat(ZOneDim, m, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bpgmm_CalculateCxy", (DL_FUNC) &_bpgmm_CalculateCxy, 7},
    {"_bpgmm_get_Z_mat", (DL_FUNC) &_bpgmm_get_Z_mat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bpgmm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
