# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateCxy <- function(m, n, hparam, thetaYList, ZOneDim, qVec, X) {
    .Call(`_bpgmm_CalculateCxy`, m, n, hparam, thetaYList, ZOneDim, qVec, X)
}

CalculatePostLambdaPsy <- function(hparam, CxyList, thetaYList, constraint) {
    .Call(`_bpgmm_CalculatePostLambdaPsy`, hparam, CxyList, thetaYList, constraint)
}

get_Z_mat <- function(ZOneDim, m, n) {
    .Call(`_bpgmm_get_Z_mat`, ZOneDim, m, n)
}

