# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateCxy <- function(m, n, hparam, thetaYList, ZOneDim, qVec, X) {
    .Call(`_bpgmm_CalculateCxy`, m, n, hparam, thetaYList, ZOneDim, qVec, X)
}

CalculatePostLambdaPsy <- function(m, p, hparam, CxyList, thetaYList, qVec, constraint) {
    invisible(.Call(`_bpgmm_CalculatePostLambdaPsy`, m, p, hparam, CxyList, thetaYList, qVec, constraint))
}

updatePostThetaY <- function(m, n, thetaYList) {
    .Call(`_bpgmm_updatePostThetaY`, m, n, thetaYList)
}

updatePostZ <- function(m, n, hparam, thetaYList, ZOneDim, qVec, constraint) {
    .Call(`_bpgmm_updatePostZ`, m, n, hparam, thetaYList, ZOneDim, qVec, constraint)
}

get_Z_mat <- function(ZOneDim, m, n) {
    .Call(`_bpgmm_get_Z_mat`, ZOneDim, m, n)
}

