# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Calculate_Cxy <- function(m, n, hparam, thetaYList, ZOneDim, qVec, X) {
    .Call(`_bpgmm_Calculate_Cxy`, m, n, hparam, thetaYList, ZOneDim, qVec, X)
}

Calculate_PostLambdaPsy <- function(m, p, hparam, CxyList, thetaYList, qVec, constraint) {
    .Call(`_bpgmm_Calculate_PostLambdaPsy`, m, p, hparam, CxyList, thetaYList, qVec, constraint)
}

Evaluate_PriorPsi <- function(psy, p, m, delta, bbeta, constraint, clusInd) {
    .Call(`_bpgmm_Evaluate_PriorPsi`, psy, p, m, delta, bbeta, constraint, clusInd)
}

Evaluate_PriorLambda <- function(p, m, alpha2, qVec, psy, lambda, constraint, clusInd) {
    .Call(`_bpgmm_Evaluate_PriorLambda`, p, m, alpha2, qVec, psy, lambda, constraint, clusInd)
}

Update_LatentScores <- function(X, thetaYList, ZOneDim, clusInd, qVec) {
    .Call(`_bpgmm_Update_LatentScores`, X, thetaYList, ZOneDim, clusInd, qVec)
}

update_PostZ <- function(X, m, n, thetaYList) {
    .Call(`_bpgmm_update_PostZ`, X, m, n, thetaYList)
}

update_Hyperparameter <- function(m, p, q, hparam, thetaYList, dVec, sVec) {
    .Call(`_bpgmm_update_Hyperparameter`, m, p, q, hparam, thetaYList, dVec, sVec)
}

get_Z_mat <- function(ZOneDim, m, n) {
    .Call(`_bpgmm_get_Z_mat`, ZOneDim, m, n)
}

dmvnrm_arma <- function(x, mean, sigma, logd) {
    .Call(`_bpgmm_dmvnrm_arma`, x, mean, sigma, logd)
}

calculate_Ratio <- function(logDeno, logNume) {
    .Call(`_bpgmm_calculate_Ratio`, logDeno, logNume)
}

